# Generated by Django 5.0.6 on 2024-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товара'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Фото'),
        ),
    ]
