# Generated by Django 5.0.6 on 2024-05-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_productimage_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='productimage',
        ),
    ]
